refactor: code Convention Setting
Junior-team/inflearn-clone2 pull request #2
Opened 2021-11-22 06:44 UTC by dldydtjs2965

### code Convention initial Setting
Eslint와 Prettier를 사용하여 airbnb를 베이스로 세팅하였으며 eslint에서 off가 된 rule들은 
저희 코드에서 생기는 문제점이므로 eslint 문서에서 확인하시고 코드 품질을 낮춘다고 생각하시면 수정 후 PR로 올려주시면
감사하겠습니다. 아래의 설정은 설정한 파일입니다.
- .eslintrc.js
```json
module.exports = {
    "env": {
        "browser": true,
        "es2021": true
    },
    "extends": [
        "airbnb-base", 
        "plugin:prettier/recommended"
    ],
    "parserOptions": {
        "ecmaVersion": 13,
        "sourceType": "script"
    },
    "settings": {
        "import/resolver": {
        "node": {
            "paths": ["src"]
            }
        }
    },
    "rules":{
        "no-use-before-define":"error",
        "no-unreachable":"error",
        "no-shadow":"error",
        "no-plusplus":"off",
        "no-param-reassign":"off",
        "no-useless-concat":"off",
        "no-await-in-loop":"off",
        "no-restricted-syntax":"off",
        "func-names":"off",
        "import/no-extraneous-dependencies":"off",
        "import/order":"off",
        "import/no-self-import":"off"
    }
};
```
- .prettierrc
```json
{
    "singleQuote": false,
    "semi": true,
    "useTabs": true,
    "tabWidth": 4,
    "trailingComma": "all",
    "printWidth": 120,
    "arrowParens": "avoid"
}
```

### workflow
- [x] 코드 컨벤션 초기 설정
- [x] 코드 아키텍처 수정
- [ ] 코드 리뷰

### 요약
**공통**
- 문자열은 쌍따옴표를 사용
- 세미콜론은 무조건 붙이고 한 개만 붙여야 합니다.
- 탭 사용 가능하며 탭 길이는 4 입니다.
- 쉼표를 사용한다면 마지막 요소에도 쉼표를 붙여야 합니다.
- 한 줄 최대 길이는 120입니다.
- 단일 파라미터에는 화살표 함수를 쓰는 것은 선택 사항입니다.

### 첨부
**참조한 링크**
- [유튜브](https://www.youtube.com/watch?v=Y3kjHM7d3Zo)
- [eslint 문서](https://eslint.org/docs/rules/)
- [airbnb 세팅](https://velog.io/@_jouz_ryul/ESLint-Prettier-Airbnb-Style-Guide%EB%A1%9C-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)

### 이슈
#1

2021-11-22 13:48 UTC, rachel490 requested changes
1.  env에 node 추가 설정 검토바랍니다.
 ```
"env": {
    "browser": false,       // 브라우저의 document와 같은 객체 사용 여부
    "node": true              // node.js에서 console과 같은 전역변수 사용 여부
      },
```
2. rules가 airbnb-base와 겹치는 부분 있어서 추가 수정이 필요해 보입니다.
3. prettier tab, tabWidth 저는 tab를 없애고 2로 설정했으면 좋겠습니다.

2021-11-23 02:13 UTC, dldydtjs2965 commented
> 1. env에 node 추가 설정 검토바랍니다.
> 
> ```
> "env": {
>    "browser": false,       // 브라우저의 document와 같은 객체 사용 여부
>    "node": true              // node.js에서 console과 같은 전역변수 사용 여부
>      },
> ```
> 
> 2. rules가 airbnb-base와 겹치는 부분 있어서 추가 수정이 필요해 보입니다.
> 3. prettier tab, tabWidth 저는 tab를 없애고 2로 설정했으면 좋겠습니다.

말씀하신 대로 수정 하였습니다 tab은 VSCODE에서 기본 탭 크기가 4라서 2로 바꾸게 되면 어색한 있어서 4로 진행할 생각입니다. rule이 겹치는 부분은 알려 주시면 감사하겠습니다.

2021-11-23 04:51 UTC, rachel490 approved these changes

2021-11-23 05:56 UTC, rachel490 approved these changes
Good!

2021-11-23 06:12 UTC, merged